---
# defaults file for roles/docker
unofficial_packages:
  - docker.io 
  - docker-compose 
  - docker-compose-v2 
  - docker-doc 
  - podman-docker 
  - containerd 
  - runc

packages:
  - ca-certificates

docker_packages:
  - docker-ce
  - docker-compose-plugin