---
# tasks file for roles/common
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"

- name: Deploy DDNS script
  ansible.builtin.template:
    src: domain.sh.j2
    dest: /usr/local/bin/domain.sh
    mode: "0755"

- name: Run DDNS script
  ansible.builtin.script: domain.sh

- name: Set cron job for DDNS script
  ansible.builtin.cron:
    name: "DNS update"
    special_time: reboot
    job: "/usr/local/bin/domain.sh"