---
# tasks file for roles/docker
- name: Uninstall unofficial packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ unofficial_packages }}"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Create a keyrings directory 
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add docker GPG
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: u+r,g+r,o+r

- name: Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker and docker compose
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"

- name: Ensure docker is started
  ansible.builtin.service:
    name: docker
    state: started

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes