---
# tasks file for roles/inception
- name: Clone inception repository
  ansible.builtin.git:
    repo: 'https://github.com/mbaanni/Inception-cloud'
    dest: /home/{{ ansible_user }}/inception

- name: Create volume folders
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ DATA_DIR }}"
    - "{{ DATA_DIR }}/wordpress"
    - "{{ DATA_DIR }}/mariadb"

- name: Render docker compose
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/inception/srcs/docker-compose.yml

- name: Start inception project
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/inception/srcs
    state: present
