---
- name: My play test
  hosts: myhosts
  become: yes
  tasks:
  - name: Update package cache
    ansible.builtin.package:
      state: latest

  - name: Install Docker Engine
    ansible.builtin.package:
      name: docker.io
      state: present
      update_cache: yes

  - name: install Make
    ansible.builtin.package:
      name: Make
      state: present

  - name: Enable and start Docker service
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Add current user to docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  - name: Clone inception project
    ansible.builtin.git:
     repo: https://github.com/mbaanni/inception.git
     dest: /home/"{{ ansible_user }}"
     clone: yes
    notify: Build Project
    